//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("WIFI OÖ GmbH")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© 2024 WIFI OÖ GmbH")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Demonstriert wie eine komponontenorientierte WPF Anwendung mit C# erstellt wird")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2024.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("3881 C# Komplettausbildung")]
[assembly: System.Reflection.AssemblyTitleAttribute("WIFI.CSharp.Teil1")]
[assembly: System.Reflection.AssemblyVersionAttribute("2024.1.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Von der MSBuild WriteCodeFragment-Klasse generiert.

