//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIFI.CSharp.Lernen {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WIFI.CSharp.Lernen.Texte", typeof(Texte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Es ist {1} Uhr... ähnelt.
        /// </summary>
        internal static string Begrüßung {
            get {
                return ResourceManager.GetString("Begrüßung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zahl {0} ist die Grenze! ähnelt.
        /// </summary>
        internal static string BinärGleich {
            get {
                return ResourceManager.GetString("BinärGleich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zahl {0} ist größer als die Grenze {1}! ähnelt.
        /// </summary>
        internal static string BinärGrößer {
            get {
                return ResourceManager.GetString("BinärGrößer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zahl {0} ist größer als oder gleich der Grenze {1}! ähnelt.
        /// </summary>
        internal static string BinärGrößerGleich {
            get {
                return ResourceManager.GetString("BinärGrößerGleich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zahl {0} ist kleiner als die Grenze {1}! ähnelt.
        /// </summary>
        internal static string BinärKleiner {
            get {
                return ResourceManager.GetString("BinärKleiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingabe nicht erkannt! ähnelt.
        /// </summary>
        internal static string Eingabefehler {
            get {
                return ResourceManager.GetString("Eingabefehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guten Abend! ähnelt.
        /// </summary>
        internal static string GrußAmAbend {
            get {
                return ResourceManager.GetString("GrußAmAbend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guten Morgen! ähnelt.
        /// </summary>
        internal static string GrußAmMorgen {
            get {
                return ResourceManager.GetString("GrußAmMorgen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grüß Gott! ähnelt.
        /// </summary>
        internal static string GrußStandard {
            get {
                return ResourceManager.GetString("GrußStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mahlzeit! ähnelt.
        /// </summary>
        internal static string GrußZuMittag {
            get {
                return ResourceManager.GetString("GrußZuMittag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo Welt! ähnelt.
        /// </summary>
        internal static string Hallo {
            get {
                return ResourceManager.GetString("Hallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Algorithmen Bausteine
        ///
        /// 1 Die Sequenz
        /// 2 Die Binärentscheidung
        /// 3 Die Fallentscheidung
        /// 4 Die Zählschleife
        /// 5 Die Abweise-Schleife
        /// 6 Die Durchlaufe-Schleife
        ///
        /// 9 Beenden
        /// ähnelt.
        /// </summary>
        internal static string Programmpunkte {
            get {
                return ResourceManager.GetString("Programmpunkte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C#&gt;  ähnelt.
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einführung in die objektorientierte Programmierung mit C# und .Net! ähnelt.
        /// </summary>
        internal static string Titel {
            get {
                return ResourceManager.GetString("Titel", resourceCulture);
            }
        }
    }
}
